version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - revive
    - gosec
    - misspell
    - unparam
    - nakedret
    - prealloc
    - bodyclose
    - noctx
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports
